### ISSUE TITLE
how to implement it with cleanmodern template ? 

### ISSUE THREAD

**Issue by nessrinehafi** [codenameone/SMSActivation#4]
hello i'm new to codename one and i don't understand how to implement it with the clean modern template?

**Comment by codenameone** [comment]
I suggest using either the discussion forum or stackoverflow for questions in the future.
This is a library, you can install it into any Codename One app by right clicking the project, selecting Codename One Settings -> Extensions and typing in SMS. Once you follow the instructions from the tool you can use this library from your code.
